---
update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: logstash-smoke-tests
    templates:
    - name: logstash_smoke_tests
      release: docker-logstash-smoke-tests
    instances: 0
    lifecycle: errand
    resource_pool: small_z1
    persistent_disk: 0
    update:
      canaries: 10
    properties:
      logstash_smoke_tests:
